name: Deploy to a dokku server

on:
  workflow_run:
    workflows: [ Unit tests ]
    branches: [ master ]
    types:
      - completed
  push:
    branches: [ master ]
    paths-ignore:
      - 'scripts/**'

jobs:
  check-dokku:
    name: Check if dokku secrets exist
    runs-on: ubuntu-latest
    outputs:
      use_dokku: ${{ steps.setvar.outputs.use_dokku }}
    steps:
      - id: setvar
        run: |
          if [[ "${{ secrets.DOKKU_HOST }}" != "" ]]; \
          then
            echo "Dokku host defined."
            echo "::set-output name=use_dokku::true"
          else
            echo "Dokku host not defined"
            echo "::set-output name=use_dokku::false"
          fi
  publish:
    needs: [check-dokku]
    if: github.event.workflow_run.conclusion == 'success' && needs.check-dokku.outputs.use_dokku == 'true' 
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: deploy
        name: Deploy to dokku
        uses: idoberko2/dokku-deploy-github-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          dokku-host: ${{ secrets.DOKKU_HOST }}
          app-name: ${{ secrets.DOKKU_APP }}
