name: Tests

on:
  push:
    branch: development
  pull_request:
    branch: development

defaults:
  run:
    working-directory: web

jobs:
  build:

    runs-on: ubuntu-latest
    container: node:12.16.3-stretch

    services:
      redis:
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - uses: danielweller-swp/postgresql-action@v2
      with:
        postgresql version: 'postgres:10.12'
        postgresql init scripts: '../database.sql'
        postgresql password: 'postgres'
        postgresql db: 'postgres'
        postgresql user: 'postgres'


    - name: Install deps
      run: npm ci

    - name: Initialize database
      run: docker exec -d postgres psql -d $DB_NAME -h $DB_HOST -f ../database.sql

    - name: Run jest
      run: npm run test

    env:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      PGPASSWORD: postgres

      REDIS_HOST: redis
      REDIS_PORT: 6379